/**
 * MockExtensionService
 */
import { IExtensionService, IUserCustomAction } from "../services";

const bogusExtensions: any = [
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'd73b2490-98bd-4c8b-bb5d-3c3be94c5632')",
    "@odata.editLink": "Web/UserCustomActions(guid'd73b2490-98bd-4c8b-bb5d-3c3be94c5632')",
    ClientSideComponentId: "bf6645bd-42e4-4a30-aad7-6ff12d61fa1f",
    ClientSideComponentProperties: "",
    CommandUIExtension: undefined,
    Description: undefined,
    Group: undefined,
    Id: "d73b2490-98bd-4c8b-bb5d-3c3be94c5632",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ListViewCommandSet",
    Name: "Item Clone",
    RegistrationId: 100,
    RegistrationType: 1,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "Item Clone",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'6835a9e0-d4d8-406c-8f0a-7a5bc37d046e')",
    "@odata.editLink": "Web/UserCustomActions(guid'6835a9e0-d4d8-406c-8f0a-7a5bc37d046e')",
    ClientSideComponentId: "a26adb40-c74c-44d0-94dc-5b69136a3d02",
    ClientSideComponentProperties:
      "{\"siteUrl\":\"https://contoso.sharepoint.com/sites/appdevhugo\", \"listName\":\"ImportantAnnouncements\"}",
    CommandUIExtension: undefined,
    Description: undefined,
    Group: undefined,
    Id: "6835a9e0-d4d8-406c-8f0a-7a5bc37d046e",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "{6835a9e0-d4d8-406c-8f0a-7a5bc37d046e}",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "Important Announcement Application Customizer",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e2')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e2')",
    ClientSideComponentId: "57fa430d-8154-4b00-b285-679314f4f390",
    ClientSideComponentProperties: "",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec26e1",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "PnP.SPFxBreadcrumb",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "PnP.SPFxBreadcrumb",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e3')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e3')",
    ClientSideComponentId: "a861c815-e425-416d-9520-04bcdf557e27",
    ClientSideComponentProperties: "",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec26e3",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "{2e5829db-79d3-4385-89f0-3258207a8aba}",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "Toastr Notifications",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e4')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e4')",
    ClientSideComponentId: "82242bbb-f951-4c71-a978-80eb8f35e4c1",
    ClientSideComponentProperties: "",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec26e4",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "{2e5829db-79d3-4385-89f0-3258207a8aba}",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "CustomFooter",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e5')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e5')",
    ClientSideComponentId: "46606aa6-5dd8-4792-b017-1555ec0a43a4",
    ClientSideComponentProperties:
      "{&quot;Top&quot;:&quot;Top area of the page&quot;,&quot;Bottom&quot;:&quot;Bottom area in the page&quot;}",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec26e4",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "{2e5829db-79d3-4385-89f0-3258207a8aba}",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "SPFxApplicationCustomizer",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e6')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e6')",
    ClientSideComponentId: "46606aa6-5dd8-4792-b017-1555ec0a43a4",
    ClientSideComponentProperties: "",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec26e6",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ListViewCommandSet.CommandBar",
    Name: "{2e5829db-79d3-4385-89f0-3258207a8aba}",
    RegistrationId: 100,
    RegistrationType: 1,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "SPFxListViewCommandSet",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e7')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e7')",
    ClientSideComponentId: "e8613642-17ee-4392-a8fd-5c0d6edcdb19",
    ClientSideComponentProperties:
      "{&quot;testMessage&quot;:&quot;Analytics&quot;}",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec26e6",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "{2e5829db-79d3-4385-89f0-3258207a8aba}",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "SPFxAnalytics",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e8')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e8')",
    ClientSideComponentId: "95483216-5d5f-404c-bf25-563e44cdd935",
    ClientSideComponentProperties: "",
    CommandUIExtension: undefined,
    Description: "Custom action for Discuss Now Command Set",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec26e8",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ListViewCommandSet",
    Name: "DiscussNowCustomAction",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "DiscussNowCommandSet",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e9')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e9')",
    ClientSideComponentId: "95483216-5d5f-404c-bf25-563e44cdd935",
    ClientSideComponentProperties: "{&quot;tasksListTitle&quot;:&quot;Tasks&quot;}",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec26e9",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "{2e5829db-79d3-4385-89f0-3258207a8aba}",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "OverdueTasks",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26ea')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26ea')",
    ClientSideComponentId: "95483216-5d5f-404c-bf25-563e44cdd935",
    ClientSideComponentProperties: "",
    CommandUIExtension: undefined,
    Description: "Opens a new page with further details about the currently selected item",
    Group: undefined,
    Id: "OpenDetailsPageWithItemReference",
    ImageUrl: undefined,
    Location: "EditControlBlock",
    Name: "{2e5829db-79d3-4385-89f0-3258207a8aba}",
    RegistrationId: undefined,
    RegistrationType: 1,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "Show Details",
    Url: "ShowDetails.aspx?ID={ItemId}&amp;List={ListId}",
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e1')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26e1')",
    ClientSideComponentId: "4017f67b-80c7-4631-b0e5-57bd266bc5c1",
    ClientSideComponentProperties:
      "{\"ClassificationPropertyBag\":\"sc_x005f_BusinessImpact\"," +
      "\"DefaultClassification\":\"LBI\", \"DefaultHandlingUrl\":\"/SitePages/Handling-instructions.aspx\"}",
    CommandUIExtension: undefined,
    Description: "Adds security classification to every site",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec26e1",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "ClassificationApplicationCustomizer",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "ClassificationApplicationCustomizer",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26eb')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26eb')",
    ClientSideComponentId: "5c715e3b-fb6f-43d7-a8a7-52bb5db34e50",
    ClientSideComponentProperties: "",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec26eb",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "{2e5829db-79d3-4385-89f0-3258207a8aba}",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "MyFavourites",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26ec')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26ec')",
    ClientSideComponentId: "6c5b8ee9-43ba-4cdf-a106-04857c8307be",
    ClientSideComponentProperties: "{&quot;targetUrl&quot;:&quot;ShowDetails.aspx&quot;}",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "OpenDetailsPageWithItemReference",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ListViewCommandSet.ContextMenu",
    Name: "{2e5829db-79d3-4385-89f0-3258207a8abc}",
    RegistrationId: undefined,
    RegistrationType: 1,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "CustomEcb",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26ed')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26ed')",
    ClientSideComponentId: "fbb38806-54e4-4ddd-a413-e7a1611fcb08",
    ClientSideComponentProperties: "{&quot;testMessage&quot;:&quot;Test message&quot;}",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec26ed",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "GraphBot",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "GraphBot",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26ee')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec26ee')",
    ClientSideComponentId: "aaa4141f-7829-4b98-af0f-a1e0e6f273fd",
    ClientSideComponentProperties: "",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec26ee",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ListViewCommandSet.CommandBar",
    Name: "SPFx-CmdEx-ExportItems",
    RegistrationId: 100,
    RegistrationType: 1,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "SPFx-CmdEx-ExportItems",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2700')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2700')",
    ClientSideComponentId: "76b03e75-7b8a-426a-86f0-c71ef1e6f38d",
    ClientSideComponentProperties: "{&quot;testMessage&quot;:&quot;Test message&quot;}",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec2700",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "GroupDirectLinks",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "GroupDirectLinks",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2701')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2701')",
    ClientSideComponentId: "42b231f6-931e-43e1-9391-6bac1ee4dcb6",
    ClientSideComponentProperties: "{&quot;testMessage&quot;:&quot;Test message&quot;}",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec2701",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "OfficeGroupsNav",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "OfficeGroupsNav",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2702')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2702')",
    ClientSideComponentId: "1b3557f3-315d-4187-8d58-60e88e93d654",
    ClientSideComponentProperties: "{&quot;testMessage&quot;:&quot;Test message&quot;}",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec2702",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "QnAChat",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "QnAChat",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2703')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2703')",
    ClientSideComponentId: "485e8b06-95bb-4a8c-b5b2-5ca0f1c28c8c",
    ClientSideComponentProperties: "{&quot;Top&quot;:&quot;Hello header!&quot;,&quot;Bottom&quot;:&quot;Hello footer!&quot;}",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec2703",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "CustomHeaderFooter",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "CustomHeaderFooter",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2704')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2704')",
    ClientSideComponentId: "3733ef6c-14dd-46c2-9a7c-a865f965920c",
    ClientSideComponentProperties: "{&quot;testMessage&quot;:&quot;Test message&quot;}",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec2704",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "SitesInHubsiteSwitcher",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "SitesInHubsiteSwitcher",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2705')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2705')",
    ClientSideComponentId: "aaa4141f-7829-4b98-af0f-a1e0e6f273fd",
    ClientSideComponentProperties:
      "{&quot;sampleTextOne&quot;:&quot;One item is selected in the list.&quot;,"
      + "&quot;sampleTextTwo&quot;:&quot;This command is always visible.&quot;}",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec2705",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ListViewCommandSet.CommandBar",
    Name: "ItemPermissions",
    RegistrationId: 100,
    RegistrationType: 1,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "ItemPermissions",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2706')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2706')",
    ClientSideComponentId: "3733ef6c-14dd-46c2-9a7c-a865f965920c",
    ClientSideComponentProperties: "",
    CommandUIExtension: undefined,
    Description: "Loads jQuery from the public CDN",
    Group: undefined,
    Id: "jQueryCDN",
    ImageUrl: undefined,
    Location: "ScriptLink",
    Name: "SitesInHubsiteSwitcher",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: "https://code.jquery.com/jquery-3.2.1.slim.min.js",
    Sequence: 100,
    Title: "jQueryCDN",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2707')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2707')",
    ClientSideComponentId: "3733ef6c-14dd-46c2-9a7c-a865f965920c",
    ClientSideComponentProperties: "",
    CommandUIExtension: undefined,
    Description: "Loads a script to rendere a custom footer",
    Group: undefined,
    Id: "spoCustomBar",
    ImageUrl: undefined,
    Location: "ScriptLink",
    Name: "SitesInHubsiteSwitcher",
    RegistrationId: undefined,
    RegistrationType: 0,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: "~SiteCollection/SiteAssets/SPOCustomUI.js",
    Sequence: 200,
    Title: "spoCustomBar",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2708')",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2708')",
    ClientSideComponentId: "a528d81e-bf9b-4463-8cda-21d76ca99243",
    ClientSideComponentProperties:
      "{&quot;sampleTextOne&quot;:&quot;One item is selected in the list.&quot;,"
      + "&quot;sampleTextTwo&quot;:&quot;This command is always visible.&quot;}",
    CommandUIExtension: undefined,
    Description: "",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec2705",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ListViewCommandSet.CommandBar",
    Name: "LockItem",
    RegistrationId: 100,
    RegistrationType: 1,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "LockItem",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2708)",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2708')",
    ClientSideComponentId: "67fd1d01-84e8-4fbf-85bd-4b80768c6080",
    ClientSideComponentProperties: "{\"SourceTermSetName\":\"Regions\"}",
    CommandUIExtension: undefined,
    Description: "Custom action for Regions Footer Application Customizer",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec2708",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "RegionsFooterCustomAction",
    RegistrationId: undefined,
    RegistrationType: 1,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "RegionsFooterCustomizer",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2709)",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec2709')",
    ClientSideComponentId: "67fd1d01-84e8-4fbf-85bd-4b80768c6080",
    ClientSideComponentProperties: "{\"TopMenuTermSet\":\"TenantGlobalNavBar\",\"BottomMenuTermSet\":\"TenantGlobalFooterBar\"}",
    CommandUIExtension: undefined,
    Description: "Custom action for Tenant Global NavBar Application Customizer",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec2709",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "TenantGlobalNavBarCustomAction",
    RegistrationId: undefined,
    RegistrationType: 1,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "TenantGlobalNavBarCustomAction",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  },
  {
    "@odata.type": "#SP.UserCustomAction",
    "@odata.id":
      "https://contoso.sharepoint.com/sites/AppDevHugo/_api/Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec270a)",
    "@odata.editLink": "Web/UserCustomActions(guid'4427baa9-bc3c-485c-a41a-a60283ec270a')",
    ClientSideComponentId: "c0c009bd-5299-4c13-9826-9068022ce804",
    ClientSideComponentProperties: "{\"WebhooksSocketServer\":\"https://webhooksbroadcaster.azurewebsites.net\"}",
    CommandUIExtension: undefined,
    Description: "Custom action for receiving webhooks notification across Socket.IO",
    Group: undefined,
    Id: "4427baa9-bc3c-485c-a41a-a60283ec270a",
    ImageUrl: undefined,
    Location: "ClientSideExtension.ApplicationCustomizer",
    Name: "WebhooksNotificationCustomAction",
    RegistrationId: undefined,
    RegistrationType: 1,
    Rights: { High: 0, Low: 0 },
    Scope: 3,
    ScriptBlock: undefined,
    ScriptSrc: undefined,
    Sequence: 0,
    Title: "WebhooksNotificationCustomizer",
    Url: undefined,
    VersionOfUserCustomAction: "16.0.1.0"
  }
];

export class MockExtensionService implements IExtensionService {
  private extensions: IUserCustomAction[];

  constructor() {
    // return a list of extensions found on https://github.com/SharePoint/sp-dev-fx-extensions
    // if there are any invalid definitions, I made the mistake -- not the respective authors of the extensions listed below
    this.extensions = bogusExtensions;
  }

  public getExtensions(): Promise<IUserCustomAction[]> {
    return new Promise<IUserCustomAction[]>((resolve: any) => {
      setTimeout(() => {
        resolve(this.extensions);
      }, 1000);
    });
  }

  public getExtensionsByUrl(url: string): Promise<IUserCustomAction[]> {
    return new Promise<IUserCustomAction[]>((resolve: any) => {
      setTimeout(() => {
        resolve(this.extensions);
      }, 1000);
    });
  }
}