define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "LoadingLabel":"extensions",
    "UnknowScopeLabel": "Unknown",
    "SiteScopeLabel": "Site",
    "WebScopeLabel": "Web",
    "ListScopeLabel": "List",
    "NAScopeLabel": "N/A",
    "NoneRegistrationTypeLabel": "None",
    "ListRegistrationTypeLabel":"List",
    "ContentTypeRegistrationTypeLabel":"ContentType",
    "ProgIdRegistrationTypeLabel":"ProgId",
    "FileTypeRegistrationTypeLabel":"FileType",
    "NARegistrationTypeLabel":"N/A",
    "ScopeHeader": "Scope",
    "TitleHeader": "Title",
    "RegistrationTypeHeader": "Registration Type",
    "LocationHeader": "Location",
    "ApplicationCustomizerLocation": "Application Customizer",
    "CommandBarLocation": "Command Bar",
    "ContextMenuLocation": "Context Menu",
    "ListViewLocation": "Command Bar/Context Menu",
    "ECBLocation": "Edit Control Block",
    "NewButton": "Add",
    "NewButtonAriaLabel": "Add. Add a new extension. Use the left or right arrow keys to navigate and the Enter key to activate.",
    "DeleteButton": "Remove",
    "UploadButton": "Upload",
    "UploadButtonAriaLabel": "Upload. Add a new extension from a PnP manifest",
    "InfoButton": "Open the details pane",
    "EditButton": "Edit",
    "EditButtonLabel": "Edit. Use the left or right arrow keys to navigate and the Enter key to activate.",
    "GroupByMenu": "Group by {0}",
    "AscendingSort": "A to Z",
    "DescendingSort": "Z to A",
    "DeleteDialogTitle": "Remove?",
    "DeleteDialogDescription": "Are you sure you want to remove the extension(s)? The solutions containing the extensions will not be removed.",
    "ClearSelectionButton": "{0} selected",
    "ClearSelectionButtonTitle": "Clear selection",
    "ClearSelectionButtonAriaLabel": "{0} selected. Use Enter key to clear selection",
    "SaveButton": "Save",
    "SaveButtonAriaLabel": "Save. Use the left or right arrow keys to navigate and the Enter key to activate.",
    "CancelButton": "Cancel",
    "CancelButtonAriaLabel": "Cancel",
  }
});